### ISSUE TITLE
Loopback: ValueError: buffer is not large enough

### ISSUE THREAD

**Issue by seppviljar** [Animator-Anon/animator_extension#10]
Whenever I check "loopback" I end up with `ValueError: buffer is not large enough` error

Apple MBP M1, 32GB RAM

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/homebrew/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/homebrew/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/sepp/stable-diffusion-webui/extensions/animator_extension/scripts/animator.py", line 78, in myprocess
    result = loopback.main_process(myset, ptxt, pimg)
  File "/Users/sepp/stable-diffusion-webui/extensions/animator_extension/scripts/functions/loopback.py", line 219, in main_process
    for idx, img in enumerate(postprocessing.morph(last_frame, post_processed_image, myset['smoothing'])):
  File "/Users/sepp/stable-diffusion-webui/extensions/animator_extension/scripts/functions/postprocessing.py", line 100, in morph
    img_list.append(Image.fromarray(arr1.astype('uint8'), 'RGBA'))
  File "/opt/homebrew/lib/python3.10/site-packages/PIL/Image.py", line 3103, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "/opt/homebrew/lib/python3.10/site-packages/PIL/Image.py", line 3019, in frombuffer
    im = im._new(core.map_buffer(data, size, decoder_name, 0, args))
ValueError: buffer is not large enough
```

**Comment by Animator-Anon** [comment]
Did latest update help?
Are you running old version of webUI?
Did you try and generate a billion smoothing frames?

**Comment by seppviljar** [comment]
Thanks, seems to work now - both tries succeeded, before that it always failed after generating the first frame.

Yes, the UI was latest and the amount of smoothing frames was around 3-5...

**Comment by Animator-Anon** [comment]
Cool, seems it is sorted. It was to do with the mode of some images being RGB instead of RGBA.
