### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Northloop** [Animator-Anon/animator_extension#2]
Ran a small test, finished without making the .mp4 but I'm on a new computer. I think I have ffmpeg installed correcly, but it didn't create an mp4

Here's the error at the end of the run.

Done. progress: 100%|██████████████████████████████████████████████████████████████| 1620/1620 [06:44<00:00,  5.73it/s]
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\extensions\animator_extension\scripts\animator.py", line 83, in myprocess
    export.make_videos(myset)
  File "C:\stable-diffusion-webui\extensions\animator_extension\scripts\functions\export.py", line 15, in make_videos
    make_mp4(myset['output_path'], 'video', final_fps, myset['vid_mp4'], False)
  File "C:\stable-diffusion-webui\extensions\animator_extension\scripts\functions\export.py", line 97, in make_mp4
    subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\micha\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Northloop** [comment]
Yeah, this was on me. I did not have ffmpeg installed in %path correctly. I do now and this issue was resolved by that.
