### ISSUE TITLE
What Am I Missing?

### ISSUE THREAD

**Issue by y0himba** [Animator-Anon/animator_extension#5]
Can someone tell me what the extension is looking for?  Is it a separate download?

![image](https://user-images.githubusercontent.com/11462603/217602220-2e9298e0-9a91-4321-960c-04d84ce75e63.png)
```
pydantic.error_wrappers.ValidationError: 4 validation errors for Options
response -> animatoranon_film_folder
  value is not None (type=type_error.not_none)
response -> animatoranon_prop_folder
  value is not None (type=type_error.not_none)
response -> animatoranon_output_folder
  value is not None (type=type_error.not_none)
response -> depthmap_script_sbsflip
  value is not None (type=type_error.not_none)
```

**Comment by Animator-Anon** [comment]
I don't know what's going on here, where are you seeing these errors? On start up? Can you post more of the log?
Are you running the latest version of Automatic's WebUI?

**Comment by y0himba** [comment]
Although I have changed nothing, now I am getting this:

```
Arguments: ('task(68qwyree3njhync)', 20, 0, 512, 512, 7, 0.4, 10.0, 15.0, 0, False, False, 0.1, -1.0, False, <PIL.Image.Image image mode=RGB size=2160x2160 at 0x23B8FB00C40>, True, True, '', '', '', True, False, False, [], []) {}
Traceback (most recent call last):
  File "C:\Tools\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Tools\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Tools\stable-diffusion-webui\extensions\animator_extension\scripts\animator.py", line 121, in myprocess
    export.make_videos(myset)
  File "C:\Tools\stable-diffusion-webui\extensions\animator_extension\scripts\functions\export.py", line 22, in make_videos
    make_gif(my_set['output_path'], 'video', final_fps, my_set['vid_gif'], False)
  File "C:\Tools\stable-diffusion-webui\extensions\animator_extension\scripts\functions\export.py", line 92, in make_gif
    subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\y0himba\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\y0himba\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Animator-Anon** [comment]
I think FFMPEG is not installed and added to the PATH system environment variable.
