### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by StingPax** [Animator-Anon/animator_extension#7]
It runs every Frame generation but at the end i get an Error in the UI and no gif or video was created, what do i wrong?

Done. progress: 100%|████████████████████████████████████████████████████████████▉| 599/600 [02:32<00:00,  4.56it/s]
Traceback (most recent call last):
  File "F:\AI\Memory Efficient Attention\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "F:\AI\Memory Efficient Attention\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "F:\AI\Memory Efficient Attention\venv\lib\site-packages\gradio\blocks.py", line 856, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\AI\Memory Efficient Attention\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\AI\Memory Efficient Attention\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\AI\Memory Efficient Attention\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\AI\Memory Efficient Attention\extensions\animator_extension\scripts\animator.py", line 84, in myprocess
    export.make_videos(myset)
  File "F:\AI\Memory Efficient Attention\extensions\animator_extension\scripts\functions\export.py", line 22, in make_videos
    make_gif(my_set['output_path'], 'video', final_fps, my_set['vid_gif'], False)
  File "F:\AI\Memory Efficient Attention\extensions\animator_extension\scripts\functions\export.py", line 92, in make_gif
    subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\TinoB\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\TinoB\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

**Comment by namion** [comment]
Same issue here:

Done. progress: 1350it [04:54,  9.53it/s]
Traceback (most recent call last):
  File "W:\AIArt\stable-diffusion-automatic\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "W:\AIArt\stable-diffusion-automatic\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "W:\AIArt\stable-diffusion-automatic\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "W:\AIArt\stable-diffusion-automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "W:\AIArt\stable-diffusion-automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "W:\AIArt\stable-diffusion-automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "W:\AIArt\stable-diffusion-automatic\extensions\animator_extension\scripts\animator.py", line 84, in myprocess
    export.make_videos(myset)
  File "W:\AIArt\stable-diffusion-automatic\extensions\animator_extension\scripts\functions\export.py", line 22, in make_videos
    make_gif(my_set['output_path'], 'video', final_fps, my_set['vid_gif'], False)
  File "W:\AIArt\stable-diffusion-automatic\extensions\animator_extension\scripts\functions\export.py", line 92, in make_gif
    subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Animator-Anon** [comment]
Do you have ffmpeg installed and available in path?

**Comment by StingPax** [comment]
> Do you have ffmpeg installed and available in path?

In wich path should it be? I do have ffmpeg installed, but it doesnt work

**Comment by StingPax** [comment]
Taped by mistake on "closed", i hate Touchscreens.

**Comment by Animator-Anon** [comment]
Install it where ever you like, but make sure it's location is in the PATH environment variable, so you can execute it from any folder. Best google how to do that on your platform.

**Comment by Animator-Anon** [comment]
Did you figure this out?
