### ISSUE TITLE
Unsupported Type?

### ISSUE THREAD

**Issue by Andie-Squirrel** [Animator-Anon/animator_extension#9]
I have been having issues after rendering out the frames. It keeps giving me errors related to JSON. I looked it up and applied a JSON dump setting to line 123:

```
with open(settings_filename, "w+", encoding="utf-8") as f:
        json.dump(myset, f, ensure_ascii=False, indent=4, default="[serializable data]")
```

And now I'm getting this error:

```
Error completing request
Arguments: ('task(44addnpl84g46im)', 20, 0, 896, 512, 7, 0.4, 1.0, 8.0, 0, False, True, 0.1, -1.0, False, <PIL.Image.Image image mode=RGB size=1334x750 at 0x1F1631CA380>, True, True, '[orange cat|red cat]', 'monochrome, colorless', '', True, False, False, 'None', 'None') {}
Traceback (most recent call last):
  File "C:\Users\Sciur\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Sciur\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Sciur\stable-diffusion-webui\extensions\animator_extension\scripts\animator.py", line 123, in myprocess
    json.dump(myset, f, ensure_ascii=False, indent=4, default="[serializable data]")
  File "C:\Program Files\Python310\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Program Files\Python310\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\Python310\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
TypeError: 'str' object is not callable
```

Prior to adding `default="[serializable data]"` to the JSON dump parameters, it yielded:

```
Error completing request
Arguments: ('task(1rfmqbw3qwipm87)', 20, 0, 896, 512, 7, 0.4, 1.0, 8.0, 0, False, True, 0.1, -1.0, False, <PIL.Image.Image image mode=RGB size=1334x750 at 0x1F18FAFC940>, True, True, '[red cat|orange cat]', 'monochrome, colorless', '', True, False, False, 'None', 'None') {}
Traceback (most recent call last):
  File "C:\Users\Sciur\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Sciur\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Sciur\stable-diffusion-webui\extensions\animator_extension\scripts\animator.py", line 123, in myprocess
    json.dump(myset, f, ensure_ascii=False, indent=4)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Program Files\Python310\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\Python310\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Image is not JSON serializable
```

**Comment by Animator-Anon** [comment]
What was the original error?

**Comment by Andie-Squirrel** [comment]
Hi. This definitely fixed the problem and I was able to render out to video.  The only issue I have is that Stable Diffusion itself doesn't seem to recognize the video exists. When I clicked the folder icon it yielded the following:

```
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  7.96it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  7.92it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  7.83it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  7.95it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  7.89it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  7.77it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  7.86it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  7.95it/s]
Done. progress: 952it [05:17,  5.76it/s]
Folder "" does not exist. After you create an image, the folder will be created.
```

Maybe I needed to change a setting? I don't know why the video isn't showing within the browser.
Thanks again for correcting the first error so quickly.

**Comment by Animator-Anon** [comment]
The video won't show in the browser, only a frame from every second's worth of video. The video should be made in the output folder, where ever that is. You can press the folder button on just below the output gallery. Even if the video file is not created, you can run one of the batch files to create it.
In the settings tab, there is an option to set a path for this extension. otherwise it will use the global txt2img and img2img paths. It will create a folder based on the time and date and stuff everything in that.

**Comment by Andie-Squirrel** [comment]
Ah, thank you very much. That was more of a feature request if anything. The folder icon doesn't do anything yet so I'll have to set the path like you said. Thanks again!

**Comment by Animator-Anon** [comment]
Ah I see what you mean. I am not sure how it would work, I would have to load the video as an object and return it from the extension..

In typical internet response fashion, the folder icon works for me! It must be tied to the issue where the output path is not clearly defined. Have you tried out a txt2img and an img2img by itself in the webui?

**Comment by Andie-Squirrel** [comment]
My apologies for not expressing myself properly. I just created a folder in Img2Img and linked it to the new folder and now, I didn't even need to render anything, when I clicked the folder it opened to that location. Thank you very much for your help!

As for loading the video as an object, maybe you can re-use the code from Deforum? They have the additional ui button that shows the video after it's been rendered.
